### ISSUE TITLE
RangeError "Offset is outside the bounds of the DataView" [opentype.parse]

### ISSUE THREAD

**Issue by Mouvedia** [bramstein/opentype#4]
"at DataView.getUint32 (native)"
https://github.com/bramstein/opentype/blob/3b7db655ae95d31d5be5d45072bac54428331330/src/type.js#L69
https://github.com/bramstein/opentype/blob/3b7db655ae95d31d5be5d45072bac54428331330/src/util.js#L66

It happens if I load source sans pro regular from http://sourceforge.net/projects/sourcesans.adobe/files/
or DejaVu from http://sourceforge.net/projects/dejavu/
It also happens with other fonts like AdobeBlank.ttf, Antinoou.ttf etc.

count seems to be the culprit
cf https://github.com/bramstein/opentype/blob/master/src/buffer.js#L57

browser affected: chrome 35

**Comment by killerbot8919** [comment]
I get this error what do i do?

 RangeError: Offset is outside the bounds of the DataView

**Comment by Hocoh** [comment]
> I get this error what do i do?
> 
> RangeError: Offset is outside the bounds of the DataView

Try to change the font you are using, for me, changing from OTF to TTF seems to have prevent this particulary bugg

**Comment by sasensi** [comment]
Hi, I am having the same issue when trying to load this font: https://github.com/google/fonts/blob/master/ofl/seoulhangang/SeoulHangang-ExtraBold.ttf  
Is there another workaround other than using another font ?

**Comment by ghost** [comment]
Same here for Google font SeoulHangang Light.
https://dropmefiles.com/1KvZU
Fires on `open` function using npm lib version 1.3.3
`RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint16 (<anonymous>)`
