### ISSUE TITLE
italicAngle: NaN

### ISSUE THREAD

**Issue by Mouvedia** [bramstein/opentype#8]
When I parse OpenSans-Italic.ttf `tables.post.italicAngle` returns `NaN`.

**Comment by Mouvedia** [comment]
Which commit fixed it?

**Comment by Mouvedia** [comment]
@bramstein Which commit fixed it?

**Comment by bramstein** [comment]
#f32989c4d19a2ad811d48f4f530c06d674e363b9 I think.
